#%RAML 0.8
title: Example Service
baseUri: http://localhost:8080/rest-adapter-generator/command/api/rest/example
version: v0.1
mediaType: application/json
protocols: [ HTTP, HTTPS ]

/users/{userId}:
  post:
    description: |
        Create user or Update user
        ...
        (mapping):
            inputType: application/vnd.people.create-user+json
            type: command
            name: people.create-user
        (mapping):
            inputType: application/vnd.people.update-user+json
            type: command
            name: people.update-user
        ...
    body:
        application/vnd.people.command.create-user+json:
            schema: !include json/schema/people.command.create-user.json
            example: !include json/create-user.json
        application/vnd.people.command.update-user+json:
            schema: !include json/schema/people.command.update-user.json
            example: !include json/update-user.json
  get:
    responses:
        200:
            body:
                application/vnd.people.query.get-user+json:
                application/vnd.people.query.get-user2+json:

/users:
  description: |
    Search users
  get:
    queryParameters:
        lastname:
            type: string
            required: true
        firstname:
            type: string
            required: false
    responses:
        200:
            description: |
                Create user or Update user
                ...
                (message):
                    mediaType: application/vnd.people.query.users+json
                    type: query
                    name: search-users
                ...
            body:
                application/vnd.people.query.users+json:
